#!/bin/bash
#!/usr/bin/env bash

# Just some prep stuff
set -o nounset
set -o errexit
set -o pipefail
# set -o xtrace

# Set magic variables for current file & dir
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"
__root="$(cd "$(dirname "${__dir}")" && pwd)" # <-- change this as it depends on your app

# And this is the actual processor code
while true
do
  TICK_UUID=`uuidgen` CREATED_AT=`date -u +"%FT%T.%3NZ"` envsubst < $__dir/schema-tick.json | jq -c -M .
  sleep 3
  # simulate kill processor (ctrl + c)
  kill -SIGINT $$
done
